import type { Metadata } from "next";
import { Michroma } from "next/font/google";
import "./globals.css";

const michromaSans = Michroma({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={michromaSans.className}>
      <body>{children}</body>
    </html>
  );
}
